ModShardTeam/ModShardLauncher

DataLoader.cs, FileReader.cs, ModLoader.cs
=> Adding comment to clarify the removal of BOM for files created by Visual Studio

.gitignore, docs/guides/how-to-play-mod.md
First pass on how-to-play-mod.md, will rewrite entirely at a later date.
To check the doc : 
- `pip install mkdocs`
- `mkdocs serve`
=> Slight improvements to the Documentation : how-to-play-mod.md

ModShardLauncherTest/ModLoaderUtilsTest.cs
=> [Minor] Work on Unit test

DataLoader.cs, FilePacker.cs, FileReader.cs, ModLoader.cs, ModLoaderUtils.cs, ModShardLauncher.csproj, Mods/Weapon.cs
Error handling for Add/Get/Set Object, GetSprite, AddCode, AddFunction, Get/Set Table, Get/Set Weapon
Some minor performance improvement
Add nullable handling with a new function (ThrowIfNull)
=> Improving error handling

README.md, docs/guides/api.en.md, mkdocs.yml
Wrote API Documentation.
Some documented methods' signatures are missing, as well as some less useful methods.
=> Wrote partial EN API Documentation

.gitignore, docs/guides/api.en.md, mkdocs.yml
Made API section of the documentation easier to navigate.
=> Improved API navigation

DataLoader.cs, FilePacker.cs, FileReader.cs, ModLoader.cs, Mods/DisassemblyEditor.cs, TextureLoader.cs
with:
- commenting TextureLoader to add some clarity
- new functions to add new texture page items and sprites from existing elements
- Some syntax improvement
=> Testing texture integration

FilePacker.cs, FileReader.cs, ModLoader.cs, ModShardLauncher.csproj, ModUtils/AsmUtils.cs, ModUtils/CodeUtils.cs, ModUtils/EventUtils.cs, ModUtils/GeneralUtils.cs, ModUtils/ObjectUtils.cs, ModUtils/RoomUtils.cs, ModUtils/TextureUtils.cs, ModUtils/VariableUtils.cs, ModUtils/Weapon.cs, ModUtils/WeaponUtils.cs, Mods/DisassemblyEditor.cs, TextureLoader.cs
- Files reorganization, ModLoader is not a catch-all file anymore
- Modding utilities methods are now located in the ModUtils folder
- Every file in ModUtils are under the same class `Msl`
- New function AddEvent and some basic cases
=> New files organisation

ModUtils/EventUtils.cs
Add a way to check if Event type and subtype are correct
=> Event cleaning

Main.xaml.cs, Pages/GeneralPage.xaml.cs
- Console sink can be silenced dynamically
- Console can be shown or hidden dynamically
- These behavior are controlled by Enable Logger option
- Settings are saved each time Enable Logger is checked/unchecked
=> Log interactivity

FilePacker.cs
FileVersion getter should work for a single file publish
=> [Fix] fileversion can be retrieved for a single file now

ModUtils/ObjectUtils.cs
As the title say, change signature and expand documentation
=> Improve add object

ModUtils/EventUtils.cs, ModUtils/ObjectUtils.cs
- Add a wrapper for events
- Add a way to add multiple events to a single object with the extension method Apply
- Add an overload for AddNewEvent
=> Improve add event

ModShardLauncherTest/CodeUtilsTest.cs, ModUtils/CodeUtils.cs
- Add a new extension method in CodeUtils
- Tested and documented
=> Improve code utils

Controls/ModInfos.xaml.cs, Controls/ModSourceInfos.xaml.cs, FileReader.cs, Main.xaml.cs, ModLoader.cs, ModUtils/AsmUtils.cs
If patching failed, display the list of mods MSL was patching (it will be useful to debug conflicts)
=> Mod in log if crash

DataLoader.cs, FileReader.cs, ModUtils/EventUtils.cs
- Add Precreate Event as a valid event
=> Precreate event

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Simple templates for easier bug reports and feature requests.
=> Updated issue templates

.gitignore, ModLoader.cs, ModShardLauncher.csproj, ModUtils/TableUtils/ConsumParam.cs, ModUtils/TableUtils/Contract.cs, ModUtils/TableUtils/CreditsBackers.cs, ModUtils/TableUtils/EnemyBalance.cs, ModUtils/TableUtils/Potion.cs, ModUtils/TableUtils/SkillsStat.cs, ModUtils/TableUtils/TableArmor.cs, ModUtils/TableUtils/TableUtils.cs, ModUtils/TableUtils/TableWeapons.cs
Added methods to inject the following tables :
- Weapons
- EnemyBalance
- Contract
- Potion
- Credits and Backers
- Armor
_This PR also disables (but doesn't fully remove) @DDDDDragon's `Weapons` class, as the implementation rewrote the `Weapons` table after mods are patched._
=> Table Injections

ModLoader.cs
Fixes #49.
Wraps objects and scripts added by MSL in conditions to check if they already exist before adding them.
=> Fixes patching of non-vanilla `.win` files

Controls/ModInfos.xaml.cs, DataLoader.cs, ModUtils/LootUtils.cs
- Fixing json not closed in resolve_loot function
- Segment resolve_loot function added by MSL into smaller function for an easier debugging
- Json created by MSL for loot table handling saved in the saving folder instead of the loading folder
- Adding durability and rarity into GuarantedTable so armors and weapons can be used in it
- Refactor Reference Table to include tiers dependency
=> Loot table fix/enhancement

ModUtils/LogUtils.cs
- Fixed file names missing zeros, 
- Increased buffer log from 16ko to 1Mo
- Fixed log data being wrapped (older data being erased)
=> [Major] fixing msl log

ModUtils/AsmUtils.cs, docs/guides/api.en.md, mkdocs.yml
Updated API documentation.
Added methods for:
- Events
- Table Injections
- Missing GML-related methods
- Mod Menu
- Disclaimer Rooms
- Loot Tables
- Rooms
=> Updated API for MSL 0.11.1.0

DataLoader.cs, ModUtils/LogUtils.cs
- Adding items/weapons/armors export in csv files
- Not sure why the fix log still appear in the diff, but it is already in main
=> Export csv
